(function(g){var window=this;'use strict';var H4=function(a){a.ra("cardstatechange",a.Lk()&&a.Qo()?1:0)},I4=function(a,b){var c=g.Wa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},xfb=function(a){var b=g.Vn(a);
a=g.mo(a);return new g.Kn(b.x,b.y,a.width,a.height)},L4=function(a){a=g.ab(a);
delete J4[a];g.kd(J4)&&K4&&K4.stop()},zfb=function(){K4||(K4=new g.Dq(function(){yfb()},20));
var a=K4;a.isActive()||a.start()},yfb=function(){var a=g.eb();
g.Zc(J4,function(b){Afb(b,a)});
g.kd(J4)||zfb()},M4=function(a,b,c,d){g.Xq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.C=null},Afb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;Bfb(a,a.progress);1==a.progress?(a.j=0,L4(a),a.onFinish(),a.rr()):a.ud()&&a.cK()},Bfb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},Cfb=function(a,b){g.zb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},N4=function(a,b,c,d,e){M4.call(this,b,c,d,e);
this.element=a},Dfb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
N4.call(this,a,b,c,d,e)},Efb=function(a){return Math.pow(a,3)},Ffb=function(a){return 3*a*a-2*a*a*a},Gfb=function(a){g.D.call(this);
this.u=a||window;this.j=[]},O4=function(a){return a.baseUrl||null},P4=function(a,b){return g.Wo(g.cn(a,b),function(c){return!!c})},Hfb=function(a,b,c){function d(ba){var fa=ba.hovercardButton;
if(!fa)return null;fa=fa.subscribeButtonRenderer;if(!fa)return null;var Ca=f(fa.unsubscribedButtonText),ea=f(fa.subscribedButtonText);if(fa.subscribed){var W=f(fa.subscriberCountWithUnsubscribeText);var Ta=f(fa.subscriberCountText)}else W=f(fa.subscriberCountText),Ta=f(fa.subscriberCountWithSubscribeText);var t=null;if(ba.signinEndpoint){t=I4(ba,"signinEndpoint","webNavigationEndpointData","url");if(!t){var Q,jb;t=null==(jb=g.S(null==(Q=fa.signInEndpoint)?void 0:Q.commandMetadata,g.A3))?void 0:jb.url}if(!t)return null}return Ca&&
(ea||t)?{subscribed:fa.subscribed,subscribeText:Ca,subscribeCount:W,unsubscribeText:ea,unsubscribeCount:Ta,enabled:fa.enabled,signinUrl:t,classic:ba.useClassicSubscribeButton}:null}
function e(ba){if(ba){var fa=[],Ca=ba.videoId;Ca&&fa.push("v="+Ca);(Ca=ba.playlistId)&&fa.push("list="+Ca);(ba=ba.startTimeSeconds)&&fa.push("t="+ba);return"/watch?"+fa.join("&")}}
function f(ba){if(!ba)return null;var fa=ba.simpleText;return fa?fa:ba.runs?g.cn(ba.runs,function(Ca){return Ca.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,v=null,y=null,A=!1,F=null,L=null,J=null,G=null,U=null,Y=null;if("VIDEO"===h)g.S(l,g.sO)?m=g.S(l,g.sO).url:(Y=g.S(l,g.rO),m=e(Y)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.S(l,g.sO)?m=g.S(l,g.sO).url:(Y=g.S(l,g.rO),m=e(Y)),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"===
h){if(A=I4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?F=d(b):L=f(b.subscribersText)}else"WEBSITE"===h?((J=I4(l,"urlEndpoint","url"))&&(m=J),n=!0,q="new",J=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(U=f(b.additionalFeesText)),(n=I4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=I4(b,"title","accessibility","accessibilityData","label");var ha=b.endpoint?b.endpoint.clickTrackingParams:null,
sa="";if(b.metadata){var oa=f(b.metadata);oa&&(sa=oa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:sa,callToAction:f(b.callToAction),DU:b.image,iconUrl:J,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,dD:p,playlistLength:v,channelId:y,subscribeButton:F,subscribersText:L,isSubscribe:A,vu:m||null,J5:n,sessionData:ha?{itct:ha}:null,C$:q,GB:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:P4(b.impressionUrls||[],O4),x5:P4(b.hovercardShowUrls||[],O4),clickUrls:P4(l.loggingUrls||[],O4),visualElement:g.jH(b.trackingParams),productPrice:G,additionalFeesText:U,watchEndpoint:Y||null}},Ifb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:P4(a.impressionUrls||[],O4),elements:P4(a.elements||[],function(d,e){return Hfb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.jH(a.trackingParams));return c},Jfb=function(a){g.XT.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.ea=!0;this.J=0;a=a.W();this.V=g.DM(a)||"profilepage"===a.Fa;this.events=new g.LK(this);g.H(this,this.events);this.events.T(this.player,g.JG("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.KG("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Kb);this.events.T(window,"focus",this.j9);this.load();var b=g.cf("STYLE");(g.Le("HEAD")[0]||document.body).appendChild(b);g.tb(this,
function(){g.qf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Kfb=function(a){return a.player.getVideoData().Dd?"current":a.V?"new":"current"},Q4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Lfb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Ifb(f,Kfb(a))));R4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.tx;d&&(c.postParams={ad_tracking:d});if(b=g.Uza(b))if(b=g.ge(b),b=g.ae(b))a.B=g.bA(b,c)},R4=function(a,b,c){c=void 0===c?!0:c;
a.player.Te("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&Mfb(a);c=[];d=new g.HG(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().u||(a.u=new g.X({G:"div",S:"ytp-ce-shadow"}),g.YS(a.player,a.u.element,4),a.C=new g.zR(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Nfb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.YS(a.player,f.element,4);var h=new g.HG(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Ofb(a,f,e)}else g.nG(new g.yB("buildEndscreenElement null",
e))}a.player.hf(c);a.Kb()}},Mfb=function(a){var b=g.lH(),c=g.mH();
c&&b&&a.endscreen.visualElement&&g.Hz(g.kQ)(void 0,c,b,a.endscreen.visualElement)},Nfb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Na:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.GB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:S4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:T4(a,b.vu),tabindex:"-1"},X:[{G:"div",Na:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.ar(b.title||"")},ya:b.title},{G:"div",S:b.dD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",ya:b.videoDuration||
void 0}]}]};c=new g.X(a);break;case "PLAYLIST":a={G:"div",Na:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.GB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:S4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:T4(a,b.vu),tabindex:"-1"},X:[{G:"div",Na:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.ar(b.title||"")},ya:b.title},{G:"div",S:"ytp-ce-playlist-count",X:[{G:"div",S:"ytp-ce-playlist-icon"},
{G:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.X(a);break;case "CHANNEL":c={G:"div",Na:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.GB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"a",Na:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:T4(a,b.vu),target:"_blank",tabindex:"-1",dir:g.ar(b.title||"")},ya:b.title},b.subscribeButton?{G:"div",S:"ytp-ce-subscribe-container",X:[{G:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{G:"div",Na:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
ya:b.metadata}:""]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:S4(b)}]};c=new g.X(c);var d=g.Me(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Lq(d,"ytp-ce-subscribe-button");if(a.player.W().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.MU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Na:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.GB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-website-title",Y:{dir:g.ar(b.title||"")},ya:b.title},{G:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{G:"a",Na:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:T4(a,b.vu),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:S4(b)},{G:"div",S:"ytp-ce-expanding-icon",Y:Pfb(b.iconUrl)}]};c=new g.X(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",S:"ytp-ce-merchandise-price-container",
X:[{G:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.X.push({G:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={G:"div",Na:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.GB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",
X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.ar(b.title||"")},ya:b.title},c,{G:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{G:"a",Na:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:T4(a,b.vu),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:S4(b)},{G:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{G:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.X(a)}b.isPlaceholder&&g.Lq(c.element,"ytp-ce-placeholder");return c},S4=function(a){if(a.DU)var b=a.DU.thumbnails;
return Pfb(b?b[b.length-1].url:null)},Pfb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Ofb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.Lq(b.element,"ytp-ce-force-expand"),U4(a,c.id,!0)):(g.Nq(b.element,"ytp-ce-force-expand"),g.Nq(b.element,"ytp-ce-element-hover"),U4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){Qfb(a,b,c)});
b.Ta("mouseleave",function(){Rfb(a,b,c)});
a.player.W().u||b.Ta("click",function(){g.Lq(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){Sfb(a,c,m)});
b.Ta("keypress",function(m){Sfb(a,c,m)});
b.Ta("focus",function(){Qfb(a,b,c)});
b.Ta("blur",function(){Rfb(a,b,c)});
b.Ta("touchstart",function(){Qfb(a,b,c)});
var l=g.Xe("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){g.RP?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.Nq(b.element,"ytp-ce-element-hover");g.Nq(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.Xe("ytp-sb-subscribe",b.element));d(g.Xe("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},Sfb=function(a,b,c){if(b.vu&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Kq(d,"ytp-ce-element");){g.Kq(d,"subscribe-label")&&Tfb(a,b);
if(g.Kq(d,"ytp-ce-channel-subscribe"))return;d=g.rf(d)}if(!d||g.Kq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Rfb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.C$)Tfb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ge(T4(a,b.vu)),g.tP(g.ae(c),void 0,b.sessionData);else{var e=g.RM(a.player.W())||a.player.getVideoData().Dd,f=function(){var h=T4(a,b.vu),l=b.sessionData,m=b.watchEndpoint,n=g.Nz(h);e&&n&&(n.v||n.list)?a.player.qo(n.v,
l,n.list,!1,void 0,m||void 0):g.BAa(h,l)};
Tfb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},T4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.YM(a)+b}else return"";return b},Qfb=function(a,b,c){g.Kq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Lq(b.element,"ytp-ce-element-hover"):a.player.W().u?(new g.Dq(function(){g.Lq(b.element,"ytp-ce-element-hover")},200)).start():g.Lq(b.element,"ytp-ce-element-hover"),V4(a,c.x5),U4(a,c.id,!0))},Rfb=function(a,b,c){g.Nq(b.element,"ytp-ce-element-hover");
g.Nq(b.element,"ytp-ce-force-expand");U4(a,c.id,!1)},U4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Pq(a.j[e].element,"ytp-ce-element-shadow-show",c)},V4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||Q4(a))c&&c();else{b=Ufb(a,b);var e=0,f=!1,h=new g.Dq(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.qD(b[a],d)}},Tfb=function(a,b,c){V4(a,b.clickUrls,c);
(a=g.mH())&&b.J5&&g.rQ(a,b.visualElement)},Ufb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Vfb(b[d],c));return a},Vfb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Wfb=function(a){return"string"===typeof a?a:""},W4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Xfb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},X4=function(a){return a.value?a.value:null},Y4=function(a){if(!a)return null;
var b=g.ge(Wfb(a.value));b=g.ae(b);if(!b)return null;var c=W4(a.target,Yfb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Xfb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Zfb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},bgb=function(a){if(!a)return null;
var b=W4(a.type,$fb),c=W4(a.trigger,agb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Y4(a?a:null);return b?new Zfb(b,c,a):null},cgb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},dgb=function(a,b){return g.Eb(a.action,b)},egb=function(a,b){this.context=a;
this.j=b},fgb=function(a){return a.customMessage?Z4("div","iv-card-message",a.customMessage):""},$4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",S:"iv-card-image",Y:{style:a},X:c}},ggb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Z4("li","",c.value));return{G:"ul",S:"iv-card-meta-info",X:b}},Z4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.ar(c);return{G:a,Y:b,ya:c}},hgb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.OB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.OB+");");c.dir=g.ar(a.customMessage);var d=[{G:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",S:"iv-card-link-icon"}));return{G:"div",Na:b,Y:c,X:d}},a5=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.dj.click,5)}},igb=function(a,b){this.merchant=a;
this.price=b},jgb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},kgb=function(a,b){return b?b:jgb(a)?"current":"new"},b5=function(a,b){g.D.call(this);
var c=this;this.element=a;this.context=b;this.wb=!1;this.eb=new Map;this.kb=new Map;this.context.I.addEventListener(g.JG("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.KG("annotations_module"),function(d){(d=c.kb.get(d))&&d.apply(c)})},c5=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.dK(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.wb=!1});
a.context.j.Ta(b,"touchmove",function(){a.wb=!0})},lgb=function(a){var b;
return(null==(b=g.S(a,g.sO))?0:b.url)?g.S(a,g.sO).url:(a=g.S(a,g.rO))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},d5=function(a,b,c){return{ZV:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
AZ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
rJ:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},mgb=function(a,b,c){b5.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Oa=this.hc=this.B=this.isInitialized=!1;this.cards=[];this.Eb=this.V=this.Ma=this.D=this.Ya=this.j=null;this.oa=[];this.qa=this.K=this.xg=this.Fa=null;this.J=0;this.Ga=new g.Dq(function(){},c.Z.Oi?4E3:3E3);
g.H(this,this.Ga);this.rb=new g.Dq(function(){});
g.H(this,this.rb);this.Ba=new egb(c,function(e,f,h,l,m,n){c5(d,e,f,h,l,m,n)});
this.ea=new g.X({G:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{G:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{G:"span",S:"iv-drawer-header-text"},{G:"button",Na:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",S:"iv-drawer-content"}]});g.H(this,this.ea);this.C=this.ea.element;this.ob=new g.zR(this.ea,330);g.H(this,this.ob);this.Yb=g.Xe("iv-drawer-header-text",this.C);this.u=g.Xe("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.hc&&e5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.hc=d.B)&&f5(d)});
this.Va=new g.LK(this);g.H(this,this.Va);this.I.addEventListener("videodatachange",this.ut.bind(this))},ngb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){e5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){f5(a)});
var c=b.headerText;g.tf(a.Yb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.jH(b.trackingParams);a.K=g.jH(b.closeTrackingParams);a.xg=g.jH(b.iconTrackingParams)},ogb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.I.W().experiments.sb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.PG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,dj:{},Ro:null,zl:e.trackingParams?g.jH(e.trackingParams):null,xg:f&&f.trackingParams?g.jH(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
OB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};g5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.PG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:h5(a,c,b,f),sponsored:!1,dj:d5(f,e,f.command),Ro:f.trackingParams?g.jH(f.trackingParams):null,zl:e.trackingParams?g.jH(e.trackingParams):null,xg:l&&l.trackingParams?g.jH(l.trackingParams):null,imageUrl:i5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.PG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,OB:null,title:f.title?g.PG(f.title):"",customMessage:f.callToAction?g.PG(f.callToAction):"",url:g.S(f.command,g.sO).url?Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.sO).url}):null,onClickCommand:null};g5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.PG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:h5(a,c,b,e),sponsored:!1,dj:d5(e,f,e.endpoint),Ro:e.trackingParams?g.jH(e.trackingParams):null,zl:f.trackingParams?g.jH(f.trackingParams):null,xg:l&&l.trackingParams?g.jH(l.trackingParams):null,channelId:g.S(e.endpoint,g.z3).browseId,customMessage:e.customText?g.PG(e.customText):null,oY:i5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.PG(e.channelName):"",metaInfo:[e.subscriberCountText?g.PG(e.subscriberCountText):""],url:Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,g.z3).canonicalBaseUrl?g.S(e.endpoint,g.z3).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,g.z3).browseId}),onClickCommand:null};g5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.PG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h5(a,c,b,e),sponsored:!1,dj:d5(e,f,e.action),Ro:e.trackingParams?g.jH(e.trackingParams):null,zl:f.trackingParams?g.jH(f.trackingParams):null,xg:l&&l.trackingParams?g.jH(l.trackingParams):null,WE:i5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.PG(e.customMessage):null,playlistVideoCount:g.PG(e.playlistVideoCount),title:e.playlistTitle?g.PG(e.playlistTitle):"",metaInfo:[e.channelName?g.PG(e.channelName):
"",e.videoCountText?g.PG(e.videoCountText):""],url:Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lgb(e.action)}),onClickCommand:null};g5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.PG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h5(a,c,b,e),sponsored:!1,dj:d5(e,f,e.action),Ro:e.trackingParams?g.jH(e.trackingParams):null,zl:f.trackingParams?g.jH(f.trackingParams):null,xg:l&&l.trackingParams?g.jH(l.trackingParams):null,WE:i5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.PG(e.lengthString):null,customMessage:e.customMessage?g.PG(e.customMessage):null,title:e.videoTitle?g.PG(e.videoTitle):"",metaInfo:[e.channelName?g.PG(e.channelName):
"",e.viewCountText?g.PG(e.viewCountText):""],isLiveNow:!!e.badge,url:Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lgb(e.action)}),onClickCommand:null};g5(a,b)}}}}}a.J++},i5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},h5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},qgb=function(a,b){if(b=pgb(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.qg.id),g.qf(b.KL),g.Jb(a.cards,b),a.UF(),j5(a)},e5=function(a,b,c){if(!a.B){a.ob.show();
a.Ya=new g.Dq(function(){g.Lq(a.context.I.getRootNode(),g.yX.IV_DRAWER_OPEN)},0);
a.Ya.start();a.Va.T(a.u,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.mH();d&&a.Fa&&a.K&&g.pQ(d,[a.Fa,a.K]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.OW||(f.OW=!0,rgb(a.context.logger,f.qg.dj.ZV,b)),d&&g.pQ(d,[f.qg.Ro]);H4(a.I);c&&(a.D=new g.Dq(function(){a.Ma=a.V;a.Eb.focus()},330),a.D.start())}},f5=function(a){a.B&&(a.ob.hide(),g.hB(a.Va),g.Nq(a.context.I.getRootNode(),g.yX.IV_DRAWER_OPEN),a.B=!1,H4(a.I),a.D&&a.D.stop(),a.D=new g.Dq(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},tgb=function(a){g.Mq(a.Bb(),
[g.yX.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.YS(a.I,a.C,5);sgb(a);a.V=g.Xe("ytp-cards-button",a.I.getRootNode());a.Eb=g.Xe("iv-drawer-close-button",a.C);a.isInitialized=!0},sgb=function(a){var b=g.Xe("iv-drawer-close-button",a.C);
a.context.j.Ta(b,"click",a.M3,a);a.context.j.Ta(a.u,"touchend",function(){a.Ga.start()});
a.context.j.Ta(a.u,"scroll",a.f4,a);a.context.u.subscribe("onHideControls",function(){a.Oa=!0});
a.context.u.subscribe("onShowControls",function(){a.Oa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Oa=g.Kq(a.I.getRootNode(),"ytp-autohide")});
a.oa.push(g.HD("iv-button-shown",a.U5,a));a.oa.push(g.HD("iv-button-hidden",a.T5,a));a.oa.push(g.HD("iv-teaser-shown",a.m0,a));a.oa.push(g.HD("iv-teaser-hidden",a.V5,a));a.oa.push(g.HD("iv-teaser-clicked",a.l0,a))},ugb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.S(b.onClickCommand,g.hcb))?void 0:c.targetId)?(a.qa=b,!0):!1},vgb=function(a,b){a.qa=b;
var c=a.I.getVideoData();if(!c)return!1;c=a.I.N("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.mya(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.S(h[0],g.VQa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},
g5=function(a,b){if(!ugb(a,b)||vgb(a,b)){var c=wgb(a,b);
if(c){var d={qg:b,KL:c.element,OW:!1};if(!b.onClickCommand){a.isInitialized||tgb(a);qgb(a,b.id);var e=xgb(a,d);g.Rb(a.cards,e,0,d);c.Ja(a.u,e);a.UF()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,j5(a),ygb(a,d),e5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&zgb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){zgb(a,d)}),j5(a))}}},wgb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{G:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=hgb(b);c={G:"div",Na:["iv-card"],X:[{G:"a",S:"iv-click-target",Y:{href:b.url?X4(b.url)||"":""},X:[$4(b.imageUrl,c),{G:"div",S:"iv-card-content",X:[Z4("h2",void 0,b.title),d]}]}]};c=new g.X(c);a5(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={G:"div",Na:["iv-card","iv-card-channel"],X:[{G:"a",Na:["iv-click-target"],Y:{href:X4(b.url)||"","data-ytid":b.channelId},X:[$4(b.oY),{G:"div",
S:"iv-card-content",X:[fgb(b),{G:"h2",S:"iv-card-primary-link",ya:b.title},ggb(b)]}]}]};c=new g.X(c);a5(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={G:"div",Na:["iv-card","iv-card-playlist"],X:[{G:"a",S:"iv-click-target",Y:{href:X4(b.url)||""},X:[$4(b.WE,{G:"div",S:"iv-card-image-overlay",X:[{G:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{G:"div",S:"iv-card-content",X:[fgb(b),Z4("h2","iv-card-primary-link",b.title),ggb(b)]}]}]};c=new g.X(c);
a5(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=hgb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({G:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={G:"div",X:e});e=b.url?X4(b.url)||"":"";c={G:"div",Na:c,Y:{tabindex:"0"},X:[{G:"a",Na:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",S:"iv-card-content",X:[b.sponsored?{G:"div",S:"iv-card-sponsored",X:["Sponsored",{G:"div",S:"iv-ad-info-container",X:[{G:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{G:"div",S:"iv-ad-info-icon-container",X:[{G:"div",S:"iv-ad-info-icon"},{G:"div",S:"iv-ad-info-callout"}]}]}]}:"",{G:"a",S:"iv-click-target",Y:{href:e},X:[Z4("h2",d,b.title),f]}]}]};c=new g.X(c);d=g.cf("span");g.tf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.qe(d,"adInfo");a5(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{G:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",Na:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={G:"div",Na:["iv-card","iv-card-video"],X:[{G:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:X4(c))||""},X:[$4(b.WE,d),{G:"div",S:"iv-card-content",X:[fgb(b),Z4("h2","iv-card-primary-link",b.title),ggb(b),f]}]}]};c=new g.X(e);a5(a,g.Ne("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},xgb=function(a,b){if(0===a.cards.length)return 0;
a=g.Fb(a.cards,function(c){return b.qg.startMs>c.qg.startMs||b.qg.startMs===c.qg.startMs&&b.qg.timestamp>=c.qg.timestamp?!0:!1});
return-1===a?0:a+1},Agb=function(a){if(a.j)return"productListing"===a.j.qg.type;
if(a.I.N("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.dn(a.cards,function(c){return"productListing"===c.qg.type})}return g.dn(a.cards,function(c){return"productListing"===c.qg.type})},j5=function(a){g.Pq(a.I.getRootNode(),"ytp-cards-shopping-active",Agb(a))},zgb=function(a,b){if(!g.Kq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.mH(),d=a.j?a.j.qg.xg:a.xg;
c&&d&&g.qQ(c,[d]);a.j=b;j5(a)}(c=a.isInitialized&&"none"==a.Bb().style.display)||(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=!(1===c||3===c||d));c||b.qg.teaserDurationMs&&a.I.sA(!0,{teaserText:b.qg.teaserText,durationMs:b.qg.teaserDurationMs,onClickCommand:b.qg.onClickCommand});a.rb.isActive()||((!a.B||!a.Ga.isActive()&&a.Oa)&&ygb(a,b),a.rb.start(910+b.qg.teaserDurationMs))}},ygb=function(a,b){a.ea.Gb?(b=new M4([0,
a.u.scrollTop],[0,b.KL.offsetTop],600,Ffb),a.context.B.Ta(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ta(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.aR(a.ea,!0),a.u.scrollTop=b.KL.offsetTop,g.aR(a.ea,!1))},k5=function(a){return a.j&&a.j.qg?a.j.qg:a.cards[0]&&a.cards[0].qg?a.cards[0].qg:null},pgb=function(a,b){return g.Eb(a.cards,function(c){return c.qg.id===b})},l5=function(a,b,c){b5.call(this,a,b);
this.annotation=c;this.isActive=!1},Bgb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},m5=function(a,b,c){l5.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},Cgb=function(a,b){var c=void 0===c?0:c;
var d=xfb(b).width;g.Tn(b,d);c=new Dfb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Efb);g.H(a,c);a.context.B.Ta(c,"begin",function(){g.no(b,!0)});
c.play()},Fgb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Na:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({G:"div",Na:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.MU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.I),a.j.Ja(d));var f=a.createElement({G:"div",Na:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Na:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.no(h,!1);var l=a.createElement({G:"div",Na:["branding-context-container-outer"]});l.appendChild(h);g.Nn(l,"right",b.image_width+"px");g.nf(a.Bb(),l);a.B=new g.Dq(function(){Dgb(a,h,l)},500);
g.H(a,a.B);a.context.j.Ta(a.Bb(),"mouseover",function(){Egb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Bb(),"mouseout",function(){a.B.start()})}},Egb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.mo(b);a.j||(b.style.width=g.Sn(f.width,!0),c.style.width=g.Sn(f.width,!0));g.Nn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Nn(d,"right","1px");a.C=!0;g.no(b,!0);a.D=new g.Dq(function(){g.Lq(this.Bb(),"iv-branding-active")},0,a);
a.D.start()}},Dgb=function(a,b,c){g.Nq(a.Bb(),"iv-branding-active");
a.J=new g.Dq(function(){g.no(b,!1);a.j||(c.style.width=g.Sn(0,!0))},250);
a.J.start();a.C=!1},Ggb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},Hgb=function(a,b,c){l5.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.ea=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({G:"div",Na:["iv-promo-contents"]});this.D=new g.Dq(function(){d.j.setAttribute("aria-hidden","true");g.no(d.B,!1);g.no(d.u,!0)},700,this);
g.H(this,this.D)},Jgb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.Bb().setAttribute("aria-hidden","true");a.Bb().setAttribute("aria-label","Promotion");a.Bb().tabIndex=0;var e=a.annotation.kf(),f=b.image_url;if(f){var h=a.createElement({G:"div",Na:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&c5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",S:"iv-promo-txt"}),g.oe(f,X4(e)),a.j=f):a.j=a.createElement({G:"div",S:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",X:[{G:"strong",ya:b.text_line_1}]});
var m=a.createElement({G:"p",X:[{G:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Na:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Na:["iv-button","iv-promo-button"],X:[{G:"span",S:"iv-button-content",ya:f}]});var p=a.createElement({G:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&c5(a,a.Bb(),e,a.annotation.id,b.session_data,void 0,c)}g.Lq(a.j,"iv-click-target");
e&&c5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",X:[{G:"span",ya:b.text_line_1}]}),m=a.createElement({G:"p",X:[{G:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Na:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.Lq(a.j,"iv-click-target"),e&&c5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);p&&a.K.appendChild(p);
c=a.createElement({G:"div",S:"iv-promo-actions"});a.u=a.createElement({G:"button",Na:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ta(a.u,"click",function(q){Igb(a,5E3,q)});
c.appendChild(a.u);g.no(a.u,!1);a.context.j.Ta(a.Bb(),"mouseover",a.a5,a);a.context.j.Ta(a.Bb(),"mouseout",a.Z4,a);a.context.j.Ta(a.Bb(),"touchend",function(q){Igb(a,5E3,q)});
a.B=a.createElement({G:"button",Na:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ta(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.V4:a.U4,a);c.appendChild(a.B);g.Mq(a.Bb(),d);h&&(g.nf(a.Bb(),h),n&&h.appendChild(n));g.nf(a.Bb(),a.K);g.nf(a.Bb(),c)},Igb=function(a,b,c){c.stopPropagation();
Kgb(a);Lgb(a,b);a.j.focus()},Mgb=function(a){a.isCollapsed||a.V||a.C||(g.Lq(a.Bb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Kgb=function(a){a.D.stop();
a.isCollapsed&&(g.Oq(a.Bb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.no(a.u,!1),g.no(a.B,!0))},Lgb=function(a,b){a.C||(a.C=g.cg(function(){Ngb(this);
Mgb(this)},b,a))},Ngb=function(a){a.C&&(g.Pa.clearTimeout(a.C),a.C=null)},Ogb=function(a){this.I=a},rgb=function(a,b,c){b&&(c?n5(a,b.map(function(d){return g.sq(d,c)})):n5(a,b))},n5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.qD(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},Pgb=function(a){g.XT.call(this,a);
var b=this;this.ea=this.K=!1;this.loadNumber=0;this.J={};this.logger=new Ogb(this.player);this.C=new g.LK(this);this.D=this.Ww=null;this.events=new g.LK(this);this.uh=this.V=this.j=null;this.oa=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ra("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.n0,this);this.subscribe("resize",this.fI,this);this.player.W().Ma.subscribe("vast_info_card_add",this.XX,this);g.H(this,this.events);this.qa=this.createElement({G:"div",S:"video-custom-annotations"});this.u=new g.X({G:"div",Na:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.YS(this.player,this.u.element,4);this.u.hide();this.B=new g.X({G:"div",Na:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",S:"video-annotations"});
a.appendChild(this.qa);this.B.element.appendChild(a);this.Nw()&&this.load();var c=this.createElement({G:"style"});(g.Le("HEAD")[0]||document.body).appendChild(c);g.tb(this,function(){g.qf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Qgb=function(a){a=a.createElement({G:"div",
Na:["annotation","annotation-type-custom"]});g.no(a,!1);return a},Rgb=function(a,b){b=!b.isCued()&&!g.zP(b,1024);
g.aR(a.u,b);g.aR(a.B,b)},Sgb=function(a,b,c){a.K=!0;
a.D=g.bA(b,c)},Tgb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Za(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Tgb(a,e))}return c},Xgb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.W().Ma.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Vz(h)&&h.responseXML?h.responseXML:null)&&Ugb(a,h)}};
g.GB()&&(d.onFinish=Vgb(a,d.onFinish));d.postParams={ic_only:"1"};Wgb(d,c);a.K=!0;g.bA(b.Va,d)}}},Wgb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.QB&&(a.postParams.ic_coll=b.QB);b.LL&&(a.postParams.ic_xml=b.LL);b.uJ&&(a.postParams.ic_track=b.uJ)},Ygb=function(a){var b=new g.X({G:"div"});
g.no(b.element,!1);var c=new mgb(a.player,b.element,o5(a));g.H(c,b);b.Ja(a.u.element);c.LE();return c},$gb=function(a,b){var c,d;
if(b=null==(c=b.Ad)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ea=!0,Zgb(a,b),b.headerText&&a.uh&&(c=g.PG(b.headerText),a.uh.setAttribute("title",c))},o5=function(a){if(!a.V){var b=new Gfb(a);
g.H(a,b);var c=new g.Sl(a);g.H(a,c);a.V=new Ggb(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.Oi)}return a.V},Ugb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.mH();if(e){var f=g.lH();f&&g.Hz(g.eCa)(void 0,e,f,[g.jH(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Tgb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=W4(f.type,ahb),p=W4(f.style,bhb),q=Wfb(f.data),r=0!==q.length?JSON.parse(q):{};var v=f.action;f=bgb;if(null==v)var y=null;else if(g.Wa(v)){l=[];for(var A=g.u(v),F=A.next();!F.done;F=A.next()){var L=f(F.value);
L&&l.push(L)}y=l}else{var J=f(v);y=J?[J]:[]}e=m&&n?new cgb(m,n,p,y,r):null}else e=null}catch(oa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=Qgb(f),U=null;switch(l.type){case "branding":if(f.player.W().Qd)break;f.u.element.appendChild(G);U=new m5(G,o5(f),l);break;case "promotion":g.YS(f.player,G,4),U=new Hgb(G,o5(f),l)}U&&U.LE();if(f=U)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Ygb(a),g.H(a,a.j));if("card"===e.type){c=a.j;var Y=e&&e.data&&e.data.card_type;
f=e.data;if(Y)switch(l=f.tracking||{},l={ZV:l.impression,click:l.click,close:l.close,AZ:l.teaser_impression,rJ:l.teaser_click},G=f.tracking_params||{},U=null,Y){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,Ro:G.card?g.jH(G.card):null,zl:G.teaser?g.jH(G.teaser):null,xg:G.icon?g.jH(G.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,oY:f.image_url,title:f.title,metaInfo:f.meta_info,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};g5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,Ro:G.card?g.jH(G.card):null,zl:G.teaser?
g.jH(G.teaser):null,xg:G.icon?g.jH(G.icon):null,WE:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};g5(c,e);break;case "productListing":f.signin_url&&(U=Y4({target:"current",value:f.signin_url}));Y=[];for(var ha=f.offers||[],sa=0;sa<ha.length;sa++)Y.push(new igb(g.Ee(ha[sa].merchant),g.Ee(ha[sa].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,Ro:G.card?g.jH(G.card):null,zl:G.teaser?g.jH(G.teaser):null,xg:G.icon?g.jH(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,OB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),ldb:U,kdb:f.signin_title?f.signin_title:void 0,jdb:f.signin_message?f.signin_message:void 0,offers:Y,onClickCommand:null};g5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,Ro:G.card?g.jH(G.card):
null,zl:G.teaser?g.jH(G.teaser):null,xg:G.icon?g.jH(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,OB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};g5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,Ro:G.card?g.jH(G.card):null,zl:G.teaser?g.jH(G.teaser):null,xg:G.icon?g.jH(G.icon):null,WE:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},g5(c,e)}}else ngb(a.j,e);c=!0}}c&&
(H4(a.player),a.fI())},Zgb=function(a,b){var c=!1;
a.j||(a.j=Ygb(a),g.H(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(ogb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.KO(f)||(c=a.j,d=b.headerText?g.PG(b.headerText):"",g.tf(c.Yb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.jH(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.jH(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.xg=b.icon.infoCardIconRenderer.trackingParams?g.jH(b.icon.infoCardIconRenderer.trackingParams):null,a.fI());H4(a.player)}},chb=function(a,b,c,d,e){if(!a.player.W().Qd){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,g.z3)&&g.S(b.navigationEndpoint,g.z3).browseId&&f.push(new Zfb("openUrl","click",new Xfb("/channel/"+g.S(b.navigationEndpoint,g.z3).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.DO)){d.channel_id=g.S(b.subscribeButton,g.DO).channelId;var l;b=g.S(b.subscribeButton,g.DO);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.PG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.PG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.PG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.PG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.S(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.A3))?void 0:m.url)||"";l={subscribeText:g.PG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.PG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new cgb(c,"branding","branding",f,d);l=Qgb(a);a.u.element.appendChild(l);f=new m5(l,o5(a),f);f.LE();g.H(f,f);a.J[c]=f}},Vgb=function(a,b){return function(){var c=g.Ha.apply(0,arguments);
a.isDisposed()||a.oa.push(g.vq.Ji(function(){b.apply(null,g.pa(c))}))}},dhb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.QS.prototype.sA=g.ca(19,function(a,b){var c=g.mU(this.Fb());c&&c.sA(a,b)});
var J4={},K4=null;g.ib(M4,g.Xq);g.k=M4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.ud())return!1;L4(this);this.startTime=a=g.eb();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.XH();this.Wl("play");-1==this.j&&this.Wl("resume");this.j=1;var b=g.ab(this);b in J4||(J4[b]=this);zfb();Afb(this,a);return!0};
g.k.stop=function(a){L4(this);this.j=0;a&&(this.progress=1);Bfb(this,this.progress);this.Wl("stop");this.rr()};
g.k.pause=function(){this.ud()&&(L4(this),this.j=-1,this.Wl("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Wl("destroy");M4.Uf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.cK=function(){this.Wl("animate")};
g.k.Wl=function(a){this.dispatchEvent(new Cfb(a,this))};
g.ib(Cfb,g.zb);g.ib(N4,M4);N4.prototype.B=function(){};
N4.prototype.cK=function(){this.B();N4.Uf.cK.call(this)};
N4.prototype.rr=function(){this.B();N4.Uf.rr.call(this)};
N4.prototype.XH=function(){this.B();N4.Uf.XH.call(this)};
g.ib(Dfb,N4);Dfb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Gfb,g.D);g.k=Gfb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.bb)(c,d||this.u);a=g.$A(a,b,c);this.j.push(a);return a};
g.k.BH=function(a,b,c,d){c=(0,g.bb)(c,d||this.u);a=g.yna(a,b,c);this.j.push(a);return a};
g.k.Mc=function(a){g.aB(a);g.Jb(this.j,a)};
g.k.Tf=function(){g.aB(this.j);this.j.length=0};
g.k.xa=function(){this.Tf();g.D.prototype.xa.call(this)};g.w(Jfb,g.XT);g.k=Jfb.prototype;g.k.load=function(){g.XT.prototype.load.call(this);if(!Q4(this)){var a=g.Vza(this.player.getVideoData());a?(a=Ifb(a,Kfb(this)),R4(this,a,!1)):Lfb(this)}};
g.k.unload=function(){R4(this,null);this.B&&(this.B.abort(),this.B=null);g.XT.prototype.unload.call(this)};
g.k.Hh=function(a,b){return Q4(this)?"loadCustomEndscreenRenderer"===a?(a=Ifb(b,"new"),R4(this,a),!0):null:null};
g.k.getOptions=function(){return Q4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Kb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ehb.length;f++){var h=Math.abs(b.width-ehb[f]);if(-1===e||d>=h)e=f,d=h}d=fhb[e];this.u&&g.Nn(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Xn(e.element,m,f);g.Tn(e.element,n,p);g.Oq(e.element,ghb);256<m||256<f?g.Lq(e.element,"ytp-ce-large-round"):96<m||96<f?g.Lq(e.element,"ytp-ce-medium-round"):g.Lq(e.element,"ytp-ce-small-round");g.Oq(e.element,hhb);m=h.left+h.width/2;h=h.top+l/2;g.Lq(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Oq(e.element,fhb);g.Lq(e.element,d);(e=g.Me(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Nn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())V4(this,this.endscreen.impressionUrls),(a=g.mH())&&this.endscreen.visualElement&&g.oQ(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.Lq(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Lq(b,"ytp-ce-shown");V4(this,c.impressionUrls);(b=g.mH())&&g.oQ(b,c.visualElement);this.player.W().J&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Nq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Nq(b,"ytp-ce-shown");this.player.W().J&&this.player.Qa("endscreenelementhidden",a)}};
g.k.j9=function(a){var b=this;a.target===window&&(new g.Dq(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Oq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ehb=[346,426,470,506,570,640,853,1280,1920],fhb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),hhb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],ghb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Yfb={hpa:"current",AOa:"new"};var $fb={CLOSE:"close",bSa:"openUrl",SUBSCRIBE:"subscribe"},agb={Mna:"click",CLOSE:"close",kAa:"hidden",RWa:"rollOut",SWa:"rollOver",rYa:"shown"};cgb.prototype.kf=function(){var a=dgb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var bhb={Nia:"anchored",D_:"branding",CHANNEL:"channel",Xoa:"cta",nAa:"highlightText",lEa:"label",PLAYLIST:"playlist",wUa:"popup",m0a:"speech",SUBSCRIBE:"subscribe",y3a:"title",VIDEO:"video",C9a:"website"},ahb={D_:"branding",Ila:"card",gra:"drawer",mAa:"highlight",kKa:"marker",MVa:"promotion",TEXT:"text",aab:"widget"};g.w(b5,g.D);g.k=b5.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.HG(a,b,{id:c,namespace:"annotations_module"});d&&this.eb.set(a,d);e&&this.kb.set(a,e);this.context.I.hf([a])};
g.k.LE=function(){this.context.u.subscribe("resize",this.UF,this)};
g.k.Bb=function(){return this.element};
g.k.dK=function(a,b,c,d,e,f){if(this.wb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.qf(this.Bb())};
g.k.UF=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=X4(a);if(f){var h=kgb(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.Dd||!1,n=g.Nz(f||"");m&&n&&(n.v||n.list)?e.context.I.qo(n.v,b,n.list,!1):g.tP(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n5(this.context.logger,c,l,d);jgb(f)||(c=g.mH(),d=b.itct,c&&d&&g.rQ(c,g.jH(d)))}};
g.k.xa=function(){this.eb.clear();this.kb.clear();g.D.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.w(mgb,b5);g.k=mgb.prototype;g.k.ut=function(){this.qa&&g5(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.mo(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.UF=function(){var a=this.isAvailable();g.no(this.Bb(),a);g.Pq(this.context.I.getRootNode(),g.yX.IV_DRAWER_ENABLED,a);H4(this.I)};
g.k.destroy=function(){this.I.sA(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.ID(this.oa);g.hB(this.Va);this.Ya&&this.Ya.dispose();this.D&&this.D.dispose();b5.prototype.destroy.call(this)};
g.k.M3=function(){if(this.B){n5(this.context.logger,k5(this).dj.close);var a=g.mH();a&&this.K&&g.rQ(a,this.K);f5(this)}};
g.k.f4=function(){g.Pq(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.U5=function(){var a=g.mH(),b=k5(this);b=b?b.xg:this.xg;a&&b&&g.pQ(a,[b])};
g.k.T5=function(){var a=g.mH(),b=k5(this);b=b?b.xg:this.xg;a&&b&&g.qQ(a,[b])};
g.k.m0=function(){var a=k5(this);n5(this.context.logger,a.dj.AZ);var b=g.mH();b&&a&&g.pQ(b,[a.zl,a.xg])};
g.k.V5=function(){var a=g.mH(),b=k5(this);a&&b&&g.qQ(a,[b.zl])};
g.k.l0=function(a){var b=k5(this),c=g.mH();this.j?a?(a=this.context.logger,n5(a,b.dj.rJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.zl&&g.rQ(c,b.zl)):(a=this.context.logger,n5(a,b.dj.rJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.xg&&g.rQ(c,b.xg)):(a=this.context.logger,n5(a,b.dj.rJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.xg&&g.rQ(c,this.xg))};g.w(l5,b5);l5.prototype.LE=function(){b5.prototype.LE.call(this);Bgb(this)};
l5.prototype.show=function(){b5.prototype.show.call(this);var a=g.mH(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.pQ(a,[g.jH(b.itct)])};
l5.prototype.hide=function(){b5.prototype.hide.call(this);var a=g.mH(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.qQ(a,[g.jH(b.itct)])};g.w(m5,l5);
m5.prototype.show=function(){if(!this.isActive){l5.prototype.show.call(this);if(!this.K){g.Lq(this.Bb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Na:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.no(this.u,!1);var b=this.createElement({G:"button",Na:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.Bb().appendChild(b);var c=this.annotation.kf();c&&c5(this,b,
c,this.annotation.id,a.session_data);Fgb(this,a);this.K=!0}g.no(this.Bb(),!0);this.isActive=!0;if(this.u){try{Cgb(this,this.u)}catch(d){}g.Lq(this.context.I.getRootNode(),"ytp-branding-shown")}}};
m5.prototype.hide=function(){this.isActive&&(l5.prototype.hide.call(this),g.no(this.Bb(),!1),this.isActive=!1,g.Nq(this.context.I.getRootNode(),"ytp-branding-shown"))};
m5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);l5.prototype.destroy.call(this)};g.w(Hgb,l5);g.k=Hgb.prototype;g.k.show=function(){this.isActive||(l5.prototype.show.call(this),this.ea||(Jgb(this),this.ea=!0),g.no(this.Bb(),!0),g.cg(function(){g.Nq(this.Bb(),"iv-promo-inactive")},100,this),this.Bb().removeAttribute("aria-hidden"),this.isActive=!0,Ngb(this),Kgb(this),Lgb(this,this.J))};
g.k.hide=function(){this.isActive&&(g.Lq(this.Bb(),"iv-promo-inactive"),this.isActive=!1,this.Bb().setAttribute("aria-hidden","true"))};
g.k.dK=function(a,b,c,d,e,f){return this.isCollapsed?!1:l5.prototype.dK.call(this,a,b,c,d,e,f)};
g.k.a5=function(a){this.V=!0;Igb(this,500,a)};
g.k.Z4=function(){this.V=!1;Mgb(this)};
g.k.U4=function(a){a.stopPropagation();this.hide()};
g.k.V4=function(a){a.stopPropagation();Ngb(this);this.isCollapsed=!0;g.Lq(this.Bb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();l5.prototype.destroy.call(this)};g.w(Pgb,g.XT);g.k=Pgb.prototype;g.k.Hh=function(a,b){if(!dhb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.J$a(b))&&Ugb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(qgb(this.j,b),H4(this.player)),!0}return null};
g.k.getOptions=function(){return dhb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Nw=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Dd&&a.oa||g.KS(this.player.app)?!1:1===c&&!b.jT||a.Ma.get(b.videoId)||g.LO(b)||g.Wza(b)?!0:!1};
g.k.fI=function(){if(this.B){var a=this.player.qb().getVideoContentRect(!0);g.Xn(this.B.element,a.width,a.height);g.Tn(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Uk();a=this.j;b=b.width;g.Pq(a.C,"iv-drawer-small",426>=b);g.Pq(a.C,"iv-drawer-big",1280<=b)}};
g.k.n0=function(a){Rgb(this,a.state);g.zP(a.state,2)&&(this.Lk()&&this.Qo()&&2!==this.player.getPresentingPlayerType()&&this.tA(!1),this.sA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Vz(h)&&h.responseXML?h.responseXML:null)&&(Ugb(b,h),g.Lq(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.XT.prototype.load.call(this);Rgb(this,this.player.Nb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.GB()&&(a=Vgb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Ma.get(d);f&&Wgb(e,f);f=f&&(f.LL||f.QB);if(!c.ZA||f)c.Va?Sgb(this,c.Va,e):(this.Ww=function(){if(!b.K)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.KO(h))&&!b.ea&&$gb(b,h)},this.player.addEventListener("videodatachange",this.Ww));
g.YS(this.player,this.B.element,4);this.fI();(f=g.LO(c))&&Zgb(this,f);(f=g.Wza(c))&&f.featuredChannel&&chb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.uh=g.Xe("ytp-cards-button",this.player.getRootNode());g.KO(c)&&$gb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&Sgb(this,b.Va,a)};
g.k.unload=function(){this.player.Te("annotations_module");for(var a=g.u(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,H4(this.player));this.K=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.J={};this.u.hide();g.XT.prototype.unload.call(this);this.B.detach();this.Ww&&(this.player.removeEventListener("videodatachange",this.Ww),this.Ww=null)};
g.k.XX=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Xgb(this):this.load())};
g.k.Lk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.Qo=function(){return!!this.j&&this.j.B};
g.k.tA=function(a,b,c){b=void 0===b?!1:b;this.Lk();this.j&&(a?c?e5(this.j,c,b):e5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):f5(this.j))};
g.k.sA=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.W().Ma.unsubscribe("vast_info_card_add",this.XX,this);g.Nq(this.player.getRootNode(),g.yX.IV_DRAWER_OPEN);for(var a=this.oa,b=g.vq,c=0,d=a.length;c<d;c++)b.Vj(a[c]);this.oa.length=0;g.XT.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.WT("annotations_module",Pgb);g.WT("creatorendscreen",Jfb);})(_yt_player);
